version: '3.7'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_UI_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":${MINIO_UI_PORT}" /data
    restart: unless-stopped

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_HOST: http://minio:${MINIO_PORT}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
    entrypoint: ["/bin/sh", "/minio-init.sh"]
    volumes:
      - ./minio-init.sh:/minio-init.sh

volumes:
  minio_data:
    driver: local
