version: '3.7'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_UI_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server --console-address ":${MINIO_UI_PORT}" /data
    restart: unless-stopped

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_HOST: http://minio:${MINIO_PORT}
      MINIO_USER: ${MINIO_USER}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
    entrypoint: ["/bin/sh", "/minio-init.sh"]
    volumes:
      - ./base-data:/base-data
      - ./minio-init.sh:/minio-init.sh

  dev_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db-seed/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./db-seed/dummy_models.sql:/docker-entrypoint-initdb.d/10-dummy_models.sql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  dev_adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: database
    restart: always
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  minio_data:
    driver: local
